title: Machine Learning for Infection and Disease
logo: "/img/logo.png?raw=true"
description:
  [About MLID Research Group](https://ayakimovich.github.io/about)
  <br>
  [Open Positions](https://ayakimovich.github.io/open_positions)
  <br>
  [Imprint](https://www.casus.science/imprint/)
  <br><br>
  Group Leader - <a href="https://scholar.google.com/citations?user=PgWk6woAAAAJ&hl=en">Artur Yakimovich, PhD</a>
 
  Follow us on <a href="https://twitter.com/ayakimovich">twitter</a> via hashtag "#YakimovichGroup"
theme: jekyll-theme-minimal
