title: Machine Learning for Infection and Disease
logo: "/img/logo.png?raw=true"
description:
  <a href="https://ayakimovich.github.io/about">About</a>
  <br>
  <a href="https://ayakimovich.github.io/open_positions">Open Positions</a>
  
  <br><br>
  Group Leader - <a href="https://scholar.google.com/citations?user=PgWk6woAAAAJ&hl=en">Artur Yakimovich, PhD</a>
  <br>
  Follow us on <a href="https://twitter.com/ayakimovich">twitter</a> via hashtag "#YakimovichGroup"
  <br><br><br>
  <a href="https://www.casus.science/imprint/">Imprint</a>
theme: jekyll-theme-minimal
